version: '3.7'

services:
  postgres:
    image: 'postgres:9.6.17-alpine'
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - dbdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  dbdata:
